# Generated by Django 3.1.7 on 2021-03-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_tittle',
            new_name='article_title',
        ),
    ]
